-- ============================================
-- PRODUCT STATUS UPDATE SCRIPT
-- ============================================
-- Total Products: 362
-- Published (Active): 134
-- Pending (Inactive): 228
-- ============================================
-- Generated: Run this script to update product status
-- ============================================

-- First, show current status distribution
SELECT status, COUNT(*) as count FROM ec_products GROUP BY status;

-- Update all products based on old database status
UPDATE ec_products SET status = 'pending' WHERE name = 'هلو كاتشب 570 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'هلو صلصة ثوم 500 مل';
UPDATE ec_products SET status = 'published' WHERE name = 'هلو صلصة تكساس برغر 500 مل';
UPDATE ec_products SET status = 'published' WHERE name = 'ابونيت خبز كراكر بالذرة 100 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ستيرلجاردا بودينج الكراميل 2 × 100 جم';
UPDATE ec_products SET status = 'pending' WHERE name = 'ستيرلجاردا بودينج الشوكولاته 200غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور كيس شيبس نكهة كاتشب الطماطم  100 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور كيس شيبس بنكهة خاصة  100 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور شيبس بنكهة ملح وخل  23 غ *14';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور شيبس بنكهة الجبنة 12*23 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور شيبس نكهة كاتشب الطماطم  23 غ * 14';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور شيبس بنكهة الزعتر 23*12';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور شيبس بنكهة الخاصة 23غ*12';
UPDATE ec_products SET status = 'pending' WHERE name = 'غندور شيبس بنكهة الحار 23غ*12';
UPDATE ec_products SET status = 'published' WHERE name = 'ابلايد نيوترشن بروتين بار كرانش شوكولاتة الحليب والفول السوداني 65 غ 21 غ بروتين';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين كاتشب الطماطم 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين صلصة البيري بيري 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين سويت صلصة البصل 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين سويت شيلي مايو 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'كوزين فيت صلصة سيزر 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين صلصة المايونيز 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين صلصة الكاري 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين صلصة تيجوانا الحارة 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت كوزين صلصة المايونيز بالثوم 425مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'ماكلويد شبس حمص 35 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'شبس بوبس بالفلفل الاحمر 85 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيجي شيبس الخضار المخبوزة 85 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'شبس بوبس كريمة وبصل 85 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ماكلويد شبس بازيلا 35 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'شبس بوبس ملح بحر 85 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ماكلويد شبس عدس 35 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كيميفين شيبس رقائق نكهة كراميل 30 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كيميفين شيبس اعواد نكهة كاتشب 30 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كيميفين شيبس تورتيلا الذرة نكهة جبنة 30 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'شبس بايوسوروس ملح 50 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ريسيز كب 124 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايكوال محلي بديل السكر 115 مغلف';
UPDATE ec_products SET status = 'pending' WHERE name = 'عروض بينزجلوتين ويفر بالفراولة 95 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'عروض بينزجلوتين ويفر بالشوكولاتة قليل بروتين 90 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'عروض بينزجلوتين اصابع مملحة 100 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بانكتوانجي شاي تشاي العضوي 24 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بانكتوانجي شاي اسود عضوي 60 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بانكتوانجي شاي جافا العضوي 24 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بانكتوانجي شاي اخضر عضوي 60 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ابو عوف جرانولا بالتوت البري 400 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ابو عوف جرانولا 400 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'فالور كرات الشوكلاتة و الحليب 200 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ترابا الواح شوكلاتة بالحليب واللوز الكامل 175 غ بدون سكر';
UPDATE ec_products SET status = 'pending' WHERE name = 'ترابا الواح شوكلاتة 80% دارك باللوز الكامل 175غ بدون سكر';
UPDATE ec_products SET status = 'published' WHERE name = 'ترابا الواح شوكلاتة 80% دارك باللوز 100غ بدون سكر';
UPDATE ec_products SET status = 'published' WHERE name = 'ترابا الواح شوكلاتة بالحليب واللوز 100 غ بدون سكر';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد كرياتين 250 غ 50 حصة فراولة وتوت';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد كرياتين 250 غ 50 حصة كرز وتفاح';
UPDATE ec_products SET status = 'pending' WHERE name = 'يابلايد كرياتين 250 غ 50 حصة مونهيدرات مايكرونايزد';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد دايت واي 1.8كغم 72حصة فراولة';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد دايت واي 1.8كغم 72حصة شوكولاته';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد ايزو 1.8كغم 72حصة شوكولاته';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد ايزو 1.8كغم 72حصة كافيه لاتيه';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد واي 2كغم 67حصة كوكيز و كريم';
UPDATE ec_products SET status = 'pending' WHERE name = 'يابلايد واي 2كغم 67حصة سيريال ميلك';
UPDATE ec_products SET status = 'published' WHERE name = 'سوبريور ايزو برو 2.2 كغم / 73 حصة - فانيلا وموز';
UPDATE ec_products SET status = 'pending' WHERE name = 'ارمي ايزو 2كغم 66حصة شوكولاتة';
UPDATE ec_products SET status = 'published' WHERE name = 'سوبريور بروتين 2.27كغم 70حصة فراولة';
UPDATE ec_products SET status = 'published' WHERE name = 'سوبريور بروتين 5كغم 156حصة شوكولاتة وبندق';
UPDATE ec_products SET status = 'published' WHERE name = 'جي ان اكس بري وورك اوت 250غ 50حصة برتقال و مانجا';
UPDATE ec_products SET status = 'published' WHERE name = 'سوبريور كيرياتين 300غ 60حصة';
UPDATE ec_products SET status = 'published' WHERE name = 'سوبريور دبليو ام بي امينو 6300 350حبة';
UPDATE ec_products SET status = 'published' WHERE name = 'سوبريور امينو 300غ 23حصة علكة';
UPDATE ec_products SET status = 'published' WHERE name = 'تاي شويز طحين الارز اللزق 500غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'تاي شويس طحين التبيوكا 500 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'صن فود سبيرولينا كرانشي 113 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ريد ميل بروتين اللوز 397 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'اي في ال ايزو 2.26كغم 72حصة شوكولاته دبل';
UPDATE ec_products SET status = 'pending' WHERE name = 'اي في ال واي 2.26كغم 56حصة شوكولاته دبل';
UPDATE ec_products SET status = 'pending' WHERE name = 'اي في ال كولاجين 330غ 30 حصة بدون نكهة';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو رايس كيك مع بذور عباد الشمس 130 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو رايس كيك كلاسيك 130 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو رايس كيك مع ملح البحر 130 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو خبز مقرمش الحنطة وبذور اليقطين 170 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو خبز مقرمش عالي الالياف 170 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو خبز مقرمش 7 بذور 170 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو خبز مقرمش 170 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو خبز مقرمش الجاودار 170 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوفو بروتين بار ويفر نكهة الكرامبل المملح  40غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوفو بروتين بار ويفر نكهة الكريمة والكوكيز 40غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوفو بروتين بار ويفر نكهة الآيس كريم فانيلا  40غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوفو بروتين بار ويفر نكهة الفراولة والكريمة  40غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو رايس كيك مع مطلي شوكولاتة الحليب  65 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو ارز سوشي ريزوتو 200 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سونكو ارز سوشي حبة مستديرة 200 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'تودي شوكولاتة داكنة 99% خ سكر 60 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'يابلايد بروتين شوفان 3كغم 50حصة شوكولاته';
UPDATE ec_products SET status = 'published' WHERE name = 'ابونيت خبز كراكر مع كينوا 100 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ابونيت خبز كراكر عضوي مع نبات حليب الشوك 100 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'عرض بينزجلوتين بسكوت شاي 130 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد ال كارنتين  480 مل 32حصة اورانج برست';
UPDATE ec_products SET status = 'pending' WHERE name = 'هلو ستيك صوص 570 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'هلو رانش صوص 500 مل';
UPDATE ec_products SET status = 'published' WHERE name = 'هلو سويت تشيلي صوص 600 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'لايكينج ملبس النعناع 50 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'فاربو ملبس الأوكالبتوس 60 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'شاي كرك نكهة الهيل 14 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'شاي كرك نكهة الزنجبيل 14 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'شاي كرك زعفران 14 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'فاربو ملبس قهوة 50 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'فاربو ملبس الفواكة 50 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بتر بودي شوفان عضوي ملفوف 454غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بتر بودي شوفان عضوي 340غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'دراجون جرانولا باللوز وحبوب الشوكولاتة العضوية 300غ';
UPDATE ec_products SET status = 'published' WHERE name = 'دراجون جرانولا كرز وجوز الهند العضوي 300غ';
UPDATE ec_products SET status = 'published' WHERE name = 'شار بسكويت سافوياردي المقرمش 200غ';
UPDATE ec_products SET status = 'published' WHERE name = 'بتر بودي فود بذور الشيا العضوية 907غ';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد ال كارنتين  480 مل 32حصة  تفاح';
UPDATE ec_products SET status = 'published' WHERE name = 'ارمي كيرياتين 300غ 60حصة';
UPDATE ec_products SET status = 'pending' WHERE name = 'كريك كروك بلس بصل وكريمة 100غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كريك كروك بلس بابريكا 100غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كريك كروك بلس هلابينو 100غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كريك كروك بلس كاتشب 100غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كريك كروك بلس باربيكيو 100غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'كريك كروك بلس اوريجينال 100غ';
UPDATE ec_products SET status = 'published' WHERE name = 'موريناجا توفو ناعمة متوسطة من املاح البحر 325غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ميجا ستار شوكولاتة 85% كيس 1 ك';
UPDATE ec_products SET status = 'published' WHERE name = 'ميجا ستار شوكولاتة 96% كيس 1 ك';
UPDATE ec_products SET status = 'published' WHERE name = 'محبوبة لاتيه بدون سكر 10 غ1*24';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك بروتين 4كغم 133حصة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'بايوتيك هايبر ماس 6.8كغم 104حصص شوكولاته';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك كيرياتين 300غ 88حصة سادة';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك EAAاحماض امينية 200حبة 50حصة';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك EAAاحماض امينية 350غ 25حصة عنب ازرق';
UPDATE ec_products SET status = 'pending' WHERE name = 'سايتك ميجا EAA احماض امينية 240حبة 60حصة';
UPDATE ec_products SET status = 'published' WHERE name = 'ايه بي اي بامب 500غ 40حصة توت ازرق';
UPDATE ec_products SET status = 'published' WHERE name = 'ايه بي اي بامب 500غ 40حصة تايجرز بلود';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد دايت واي 1كغم 40حصة فانيلا ايسكريم';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتري فيرسوم ليمتلس طاقة قبل التمرين 380غ 20حصة علكة';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتري فيرسوم سيترولين مالات 200غ 40حصة';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتري فيرسوم واي 1كغم 33حصة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتري فيرسوم واي 1كغم 33حصة فراولة';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتري فيرسوم ايزو 1كغم 40حصة شوكولاته بالحليب';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتري فيرسوم ايزو 1كغم 40حصة شوكولاته بيضاء بالفراولة';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتري فيرسوم ال كارنتين 500مل 20حصة توت';
UPDATE ec_products SET status = 'pending' WHERE name = 'يابلايد دايت واي 1.8كغم 72حصة فانيلا ايسكريم';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد ايزو 1.8كغم 72حصة فراولة';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد ايزو 1.8كغم 72حصة فانيلا';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد دايت واي 1.8كغم 72حصة موز';
UPDATE ec_products SET status = 'pending' WHERE name = 'شادو ايزو 2ك 66حصة شوكولاته';
UPDATE ec_products SET status = 'published' WHERE name = 'زيرو كانديز ملبس الكراميل 32 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'لابرادا ايزو  عرض مع كرياتين';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك واي 1كغم 35حصة موز';
UPDATE ec_products SET status = 'pending' WHERE name = 'بايوتيك ايزو 2.27كغم 90حصة فراولة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بايوتيك ايزو 2.27كغم 90حصة بستاشيو';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك EAAاحماض امينية 350غ 25حصة تفاح';
UPDATE ec_products SET status = 'pending' WHERE name = 'اف ايه اوميجا 3  90حبة 126غ';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك EAAاحماض امينية 350غ 25حصة ليمون ايس تي';
UPDATE ec_products SET status = 'pending' WHERE name = 'شادو ماسجينر 6ك 40حصة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'شادو هايدرو 2.27ك 90حصة كوكيز اند كريم';
UPDATE ec_products SET status = 'pending' WHERE name = 'شادو هايدرو 2.27ك 90حصة فانيلا';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد واي 450غ 15حصة فانيلا ايس كريم';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد دايت واي 450غ 18حصة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'يابلايد دايت واي 450غ 18حصة فانيلا ايس كريم';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد دايت واي 450غ 18حصة كراميل مملح';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد دايت واي 450غ 18حصة فراولة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار كراميل بالفول السوداني 50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار كراميل بالفول السوداني 70غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار بالتمر 50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار بالتمر 70غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار شوكولاته براوني 50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار شوكولاته براوني 70غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار شوكولاته بيضاء بجوز الهند والاناناس 50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار كراميل 70غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين بار دبل تشوكلت 70غ';
UPDATE ec_products SET status = 'published' WHERE name = 'باد اس جينابولك 3 كغم 60سكوب 15حصة بالفراولة';
UPDATE ec_products SET status = 'published' WHERE name = 'باد اس جينابولك 3 كغم 60سكوب 15حصة بالفانيلا';
UPDATE ec_products SET status = 'published' WHERE name = 'سوبر دوبر مصاص خالي من السكر بالفيتامينات والمعادن';
UPDATE ec_products SET status = 'pending' WHERE name = 'جريناد بروتين شيك شوكولاته بالنعناع 330 مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'بينزجلوتين خليط الشوفان الفوري ٣٠٠غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بينزجلوتين ميوزلي بالفواكه المجففة 250 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بينزجلوتين خميرة 7غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ترابا ستيفيا الواح شوكلاتة بالحليب والبندق 75غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ترابا كيس شوكولاته مكعبات ستيفيا 1كغم';
UPDATE ec_products SET status = 'published' WHERE name = 'ترابا مسحوق الكاكاو 250 جرام';
UPDATE ec_products SET status = 'published' WHERE name = 'ترابا الواح شوكولاته بالحليب وقطع البندق 95غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ترابا لوح شوكولاته بالحليب وقطع اللوز 95غ';
UPDATE ec_products SET status = 'published' WHERE name = 'كيفين ل كارنيتين سائل 33حصة 500مل بلو روزبيري';
UPDATE ec_products SET status = 'pending' WHERE name = 'باد اس ل كارنيتين سائل 33حصة 500مل كولا و كرز';
UPDATE ec_products SET status = 'pending' WHERE name = '1881 معكرونة سباجيتي خالية من الغلوتين 400 غ';
UPDATE ec_products SET status = 'pending' WHERE name = '1881 باستا خالي جلوتين 400غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 2.27 كغم 73 حصة تفاح وقرفة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 2.27 كغم 73 حصة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد بيف ايزو 1.8 كغم 51 حصة فانيلا';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد هايدرو ايزو 2.27 كغم 81 حصة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 1 كغم 32 حصة كراميل مملح';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 1 كغم 32 حصة تفاح وقرفة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 1 كغم 32 حصة موز';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 500غ 16 حصة كراميل مملح';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 500غ 16 حصة موكا كابتشينو';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد جلوتامين 300غ 60 حصة بدون نكهة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 500غ 16 حصة فراولة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد واي 500غ 16 حصة تفاح وقرفة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد بيتا الانين 200غ 100 حصة بدون نكهة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد بيف ايزو 908غ 25 حصة فانيلا';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد ارجينين 100 حبة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد فيتارجو 1.8 كغم 50 حصة فواكه';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد كيرياتين 300غ 55 حصة تفاح';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد كيرياتين 300غ 55 حصة برتقال';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد فيتارجو 1.8 كغم 50 حصة عنب';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد كاربو 1.8 كغم 36 حصة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد كيرياتين 300غ 55 حصة كرز';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد CGT ماكس 600غ 30 حصة توت';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد كيرياتين 300غ 60 حصة بدون نكهة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد كولاجين 90 حبة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بيلد cyro سيل 477غ 30 حصة بطيخ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد ل كارنتين سائل 500مل 50 حصة برتقال';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد ل كارينتين سائل 500 مل 50 حصة مانجو';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد CRYO بيف 300 حبة 75 حصة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد امينو 300 حبة 75 حصة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد سيترولين 200غ 66 حصة بدون نكهة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد EAA غ360 30 حصة بطيخ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد ماس 5.4 كغم 108 حصة شوكولاتة';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد كيرياتين 300غ 100 حصة بدون نكهة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بيج مان ماس 3 كغم 20 حصة شوكليت ميلك شيك';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفر بلد ماس 5.4 كغم 108 حصة فانيلا';
UPDATE ec_products SET status = 'pending' WHERE name = 'بيج مان كاربو 2 كغم 57 حصة فواكه الغابة';
UPDATE ec_products SET status = 'published' WHERE name = 'سانتي جرانولا فول سوداني 350غ';
UPDATE ec_products SET status = 'published' WHERE name = 'سانتي جولد جرانولا مكسرات بالعسل 300غ';
UPDATE ec_products SET status = 'published' WHERE name = 'سانتي جرانولا فراولة كرانبيري كرز 350غ';
UPDATE ec_products SET status = 'published' WHERE name = 'سانتي كرانشي كلاسيك ميوزلي 350 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'اوليمب بيتا الانين 250غ';
UPDATE ec_products SET status = 'published' WHERE name = 'اوليمب بي سي ايه اكسبلود 280غ 28حصة برتقال';
UPDATE ec_products SET status = 'published' WHERE name = 'اوليمب ارجي باور 120حبة';
UPDATE ec_products SET status = 'pending' WHERE name = 'جود كالوريز ميني بار بالكاجو بلوبيري مافن 102غ 17غ×6';
UPDATE ec_products SET status = 'pending' WHERE name = 'جود كالوريز ميني بار بالكاجو والتوت 102غ 17غ×6';
UPDATE ec_products SET status = 'pending' WHERE name = 'جود كالوريز ميني بار بالكاجو تشيز كيك 102غ 17غ×6';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتريك كرات بالكاكاو عضوية 250غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتريك + مكعبات الأرز العضوي محشوة بالكاكاو 375 جم';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتريك كوكيز شوفان عضوي 200غ.';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتريك كوكيز شوفان عضوي شوكولاته وبرتقال 200غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'نوتريك كوكيز شوفان عضوي كينوا ارونيا 200غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'السابور  ناتشوز 100غ مملح';
UPDATE ec_products SET status = 'pending' WHERE name = 'السابور شيبس الناتشوز 200 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر ايزو 1.81كغم 63حصة شوكولاتة وجوز الهند';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر ايزو 1.81كغم 63حصة شوكولاتة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر ايزو 1.81كغم 63حصة شوكولاتة وفول سوداني';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر ايزو 1.81كغم 63حصة كوكيز وكريمة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر ايزو 1.81كغم 63حصة فانيلا وكريمة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي بيلدر ماس جينر 4.56كغم  45سكوب شوكولاتة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي بيلدر ماس جينر 4.56كغم 45سكوب  فانيلا';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي بيلدر ماس جينر 2.27كغم 22سكوب فانيلا';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر واي نيترو كرياتين 1.81كغم 37 حصة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر واي 4.5 كغم 135حصة  شوكولاتة وحليب';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر واي 1.81.كغم 54حصة فراولة';
UPDATE ec_products SET status = 'pending' WHERE name = 'بودي  بيلدر واي 1.81 كغم 54 حصة شوكولاتة وحليب';
UPDATE ec_products SET status = 'pending' WHERE name = 'لابيرفا امينو 7500 اسيد 300قرص';
UPDATE ec_products SET status = 'pending' WHERE name = 'لابيرفا امينوEAA 390غ 30حصة كاندي';
UPDATE ec_products SET status = 'published' WHERE name = 'لايكينج ملبس عرق السوس 50 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'باندي سوس بطعم الخوخ 50 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'لازار واي 1كغم 33حصة شوكولاته';
UPDATE ec_products SET status = 'published' WHERE name = 'لازار واي 1كغم 33حصة فراولة';
UPDATE ec_products SET status = 'published' WHERE name = 'لازار واي 2.27كغم 75حصة شوكولاتة';
UPDATE ec_products SET status = 'published' WHERE name = 'لازار واي 2.27كغم 75حصة فراولة و موز';
UPDATE ec_products SET status = 'pending' WHERE name = 'لازار ايزو 25غ حصة واحدة شوكولاته';
UPDATE ec_products SET status = 'pending' WHERE name = 'لازار ايزو 25غ حصة واحدة كراميل مملح';
UPDATE ec_products SET status = 'pending' WHERE name = 'ابو عوف بار مكسرات باللوز والبريتزل المملح 40غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'لابيرفا شوربة سريعة التحضير كريمة بنكهة الدجاج 4*17غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'لابيرفا شوربة سريعة التحضير نكهات متنوعة 4 *17غ';
UPDATE ec_products SET status = 'published' WHERE name = 'كوسكا راحة مشكلة خالي جلوتين 250غ';
UPDATE ec_products SET status = 'published' WHERE name = 'كوسكا راحة بالمكسرات خالي جلوتين 250غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سيليني كبسولات بدون كافيين نيسبريسو 55 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'سيليني كبسولات بدون كافيين دولشي 75 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'سي فور مشروب طاقة بطعم  500 مل';
UPDATE ec_products SET status = 'published' WHERE name = 'سي فور مشروب طاقة بطعم فراولة  500 مل';
UPDATE ec_products SET status = 'published' WHERE name = 'سي فور مشروب طاقة بطعم كوزميك رينبو 500مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'ابسو موف بار فانيلا وجوز هند نباتي 35 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بسكويت شوفان بالكاجو والزبيب 30غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بسكويت شوفان بالفول السوداني 30غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بسكويت شوفان كلاسيك 30غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بسكويت شوفان بالزبيب 30غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين شيبس بالبرايم ريبس 50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين شيبس بالكاتشب 50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين شيبس بالفلفل الحلو  50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين شيبس بالساور كريم والبصل  50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين حلقات بالجبنة الايطالية 50غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو بروتين حلقات بالجبنة بارميزان 50غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ايفولف زيرو بروتين بايتس لوز بالتمر ستيفيا 30غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ايفولف زيرو بروتين بايتس دبل تشوكلت ستيفيا 30غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاته دبي كريمة جوز هند ستيفيا 100غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاته دبي بستاشيو ستيفيا 90غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاته دبي بالبندق ستيفيا 90غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ايفولف زيرو بروتين بايتس لوتس ستيفيا 30غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ايفولف زيرو بروتين بايتس موكا ستيفيا 30غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ايفولف زيرو بروتين بايتس كوكيز اند كريم ستيفيا 30غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ايفولف زيرو بروتين بايتس كاجو كراميل ستيفيا 30غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'نايتشرز باث حبوب الافطار العضوية شوكولاته و فراولة شكل سلحفاة 284غ';
UPDATE ec_products SET status = 'published' WHERE name = 'توبس دراجيه شوكولاته بيضاء بالبيستاشيو 250غ';
UPDATE ec_products SET status = 'published' WHERE name = 'توبس الواح شوكولاته بالحليب 100غ';
UPDATE ec_products SET status = 'published' WHERE name = 'توبس الواح شوكولاته بالحليب والبندق 100غ';
UPDATE ec_products SET status = 'published' WHERE name = 'توبس الواح شوكولاته داكنة 70% 100غ';
UPDATE ec_products SET status = 'published' WHERE name = 'توبس الواح شوكولاته بالحليب واللوز 100غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'بومبوس بروتين 30% كراميل مملح 50غ';
UPDATE ec_products SET status = 'published' WHERE name = 'كوكو لايف حليب جوز هند بودرة 300غ';
UPDATE ec_products SET status = 'published' WHERE name = 'كوكو لايف طحين جوز هند عضوي 500غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاتة بيضاء 500غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاتة الحليب ستيفيا500غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاتة  بستاشيو ستيفيا 500غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاتة بالبندق ستيفيا500غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاتة كاجو ستيفيا 500غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ايفولف زيرو شوكولاتة القهوة ستيفيا  500غ';
UPDATE ec_products SET status = 'published' WHERE name = 'جي ان اكس ذا ريبر حارق دهون 150غ 30حصة اناناس';
UPDATE ec_products SET status = 'published' WHERE name = 'جي ان اكس ذا ريبر حارق دهون 150غ 30حصة بلو روزبيري';
UPDATE ec_products SET status = 'published' WHERE name = 'جي ان اكس بري وورك اوت 250غ 50حصة دارك جريب';
UPDATE ec_products SET status = 'pending' WHERE name = 'برستيج بسكويت كاكاو 102 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'برستيج بسكويت الشوفان 102 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'روبيكون عصير فواكة ليتشي 1لتر';
UPDATE ec_products SET status = 'published' WHERE name = 'روبيكون عصير فواكة ورمان  1لتر';
UPDATE ec_products SET status = 'published' WHERE name = 'روبيكون شراب  جوز الهند االعضوي 1لتر';
UPDATE ec_products SET status = 'published' WHERE name = 'روبيكون شراب توت وفواكة 200مل';
UPDATE ec_products SET status = 'published' WHERE name = 'روبيكون شراب اناناس وجزر وبرتقال  200مل';
UPDATE ec_products SET status = 'published' WHERE name = 'روبيكون شراب اناناس وجوز الهند  200مل';
UPDATE ec_products SET status = 'published' WHERE name = 'روبيكون شراب فواكة استوائية 200مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'بورمار سوس 100غ';
UPDATE ec_products SET status = 'published' WHERE name = 'جو زيروشوكولاته دهن رايس كريسبي 227غ';
UPDATE ec_products SET status = 'published' WHERE name = 'جولون بسكويت دايجستيف قمح 245غ';
UPDATE ec_products SET status = 'published' WHERE name = 'كيتارا بسكويت سادة 150 غ';
UPDATE ec_products SET status = 'pending' WHERE name = 'ارمي ايزو 4.54كغم 151حصة روزبيري';
UPDATE ec_products SET status = 'pending' WHERE name = 'سوبريور هايدرو 2.2كغم 66حصة جوزهند و اناناس';
UPDATE ec_products SET status = 'pending' WHERE name = 'سوبريور هايدرو 2.2كغم 66حصة كوكيز اند كريم';
UPDATE ec_products SET status = 'pending' WHERE name = 'سوبريور هايدرو 2.2كغم 66حصة كيكة عيد الميلاد';
UPDATE ec_products SET status = 'published' WHERE name = 'مسل لابس جينر 4.45كغم 30 حصة 60 سكوب شوكولاته';
UPDATE ec_products SET status = 'published' WHERE name = 'ذا بريدج حليب الشوفان بريستا عضوي 500 ملم';
UPDATE ec_products SET status = 'published' WHERE name = '1 بيج لاين ويفر حمضيات خالي من السكر 35 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'بيرفورم بروتين بار 62 غ شوكولاتة';
UPDATE ec_products SET status = 'published' WHERE name = 'بايوتيك واي 28غ حصة واحدة كوكيز و كريمة';
UPDATE ec_products SET status = 'pending' WHERE name = 'هيلثي كولا كولا 250مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'هيلثي كولا برتقال 250مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'هيلثي كولا تفاح اخضر 250مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'هيلثي كولا اناناس 250مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'هيلثي كولا ليمون ونعنع 250مل';
UPDATE ec_products SET status = 'pending' WHERE name = 'هيلثي كولا مكس بيري 250مل';
UPDATE ec_products SET status = 'published' WHERE name = 'لايت بايت كعكة الارز والذرة 24غ عسل و خردل';
UPDATE ec_products SET status = 'published' WHERE name = 'لايت بايت كعكة الارز والذرة 24غ فلفل و ليمون';
UPDATE ec_products SET status = 'published' WHERE name = 'ارمي امينو 300غ 23حصة مانجا و باشن فروت';
UPDATE ec_products SET status = 'published' WHERE name = 'فيت فيوجين واي 1 حصة';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت فيوجين بري وورك اوت 1 حصة برتقال';
UPDATE ec_products SET status = 'pending' WHERE name = 'فيت فيوجين جلوتامين 1 حصة فراولة';
UPDATE ec_products SET status = 'published' WHERE name = 'فيت فيوجين واي 1 حصة فراولة';
UPDATE ec_products SET status = 'published' WHERE name = 'فيت فيوجين واي 1 حصة شوكولاتة';
UPDATE ec_products SET status = 'published' WHERE name = 'فيت فيوجين واي 1 حصة كابتشينو';
UPDATE ec_products SET status = 'published' WHERE name = 'فيتا جوز الهند والفراولة 320مل';
UPDATE ec_products SET status = 'published' WHERE name = 'الكسيح  كاكاو طبيعي 150غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ميكسيتا تورتيلا بالملح 150 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'كوكو لايف رقائق جوز الهند 500 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'يابلايد بيف جينر 3130 غ 75 حصة اناناس';
UPDATE ec_products SET status = 'published' WHERE name = 'بايسكس واي بروتين 2.25 كغم نكهة فراولة 70 حصة';
UPDATE ec_products SET status = 'published' WHERE name = 'كاستيللو نوغا 200 غ توستادا';
UPDATE ec_products SET status = 'published' WHERE name = 'كاستيللو نوغا 150 غ لوز و عسل';
UPDATE ec_products SET status = 'pending' WHERE name = 'كوليوس لبن هيرقل عالي بروتين 0% 500 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'ذا بيغيننغز براوني بار فانيلا 40غ';
UPDATE ec_products SET status = 'published' WHERE name = 'جرانيو بار فول سوداني 30 غ شيا و كتان';
UPDATE ec_products SET status = 'published' WHERE name = 'جرانيو بار فول سوداني 30 غ برتقال';
UPDATE ec_products SET status = 'published' WHERE name = 'جرانيو بار فول سوداني 30 غ جوز الهند';
UPDATE ec_products SET status = 'published' WHERE name = 'رايدر بروتين بار فول سوداني و كراميل مملح 50 غ';
UPDATE ec_products SET status = 'published' WHERE name = 'فيت فيوجين ماس 2.75 ك 8 حصص شوكولاتة';
UPDATE ec_products SET status = 'published' WHERE name = 'لايت اند سويت سابليه 400 غ';

-- Verify the updates
SELECT status, COUNT(*) as count FROM ec_products GROUP BY status;
